### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by memoryskull** [iRebbok/RainbowPlayerList#1]
Hi @iRebbok 
I would like to collaborate with a logo for this Rainbow tool

**Comment by iRebbok** [comment]
What do you mean?

**Comment by memoryskull** [comment]
@iRebbok 
I'm interested in collaborating with this project by delivering a series of logotype options that fits this project for the best!

If interested let me know so we can get started!

Cheers!

**Comment by iRebbok** [comment]
I think you're wrong, it's not a project, it's just a plugin.
And more he will not leave.

**Comment by iRebbok** [comment]
I'm closing this issue.
